In [34]:
A = rand(3,3)
B = rand(3,3)
U,V,Q,C,S,R = svd(A,B)
H = R*Q'

3×3 Array{Float64,2}:
  1.28299    0.399955   0.280971
 -0.417036  -0.752499  -0.582209
  1.26205    0.406697   0.913254

In [35]:
U*C*H

3×3 Array{Float64,2}:
 0.986975  0.0874971  0.0693731
 0.827839  0.672742   0.538702 
 0.35533   0.182805   0.0445336

In [36]:
A

3×3 Array{Float64,2}:
 0.986975  0.0874971  0.0693731
 0.827839  0.672742   0.538702 
 0.35533   0.182805   0.0445336

In [20]:
?svd

search: svd svds svdvals svdfact svdvals! svdfact! isvalid



```
svd(A, thin::Bool=true) -> U, S, V
```

Computes the SVD of `A`, returning `U`, vector `S`, and `V` such that `A == U*diagm(S)*V'`. The singular values in `S` are sorted in descending order.

If `thin=true` (default), a thin SVD is returned. For a $M \times N$ matrix `A`, `U` is $M \times M$ for a full SVD (`thin=false`) and $M \times \min(M, N)$ for a thin SVD.

`svd` is a wrapper around [`svdfact`](@ref), extracting all parts of the `SVD` factorization to a tuple. Direct use of `svdfact` is therefore more efficient.

# Example

```jldoctest
julia> A = [1. 0. 0. 0. 2.; 0. 0. 3. 0. 0.; 0. 0. 0. 0. 0.; 0. 2. 0. 0. 0.]
4×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  2.0
 0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0

julia> U, S, V = svd(A)
([0.0 1.0 0.0 0.0; 1.0 0.0 0.0 0.0; 0.0 0.0 0.0 -1.0; 0.0 0.0 1.0 0.0], [3.0, 2.23607, 2.0, 0.0], [-0.0 0.447214 -0.0 0.0; 0.0 0.0 1.0 0.0; … ; -0.0 0.0 -0.0 1.0; 0.0 0.894427 0.0 0.0])

julia> U*diagm(S)*V'
4×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  2.0
 0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0
```

```
svd(A, B) -> U, V, Q, D1, D2, R0
```

Wrapper around [`svdfact`](@ref) extracting all parts of the factorization to a tuple. Direct use of `svdfact` is therefore generally more efficient. The function returns the generalized SVD of `A` and `B`, returning `U`, `V`, `Q`, `D1`, `D2`, and `R0` such that `A = U*D1*R0*Q'` and `B = V*D2*R0*Q'`.
